version: '3.7'

services:
  haproxy:
    image: "haproxy:1.8.14"
    ports:
     - "80:80"
    volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
     - mynet
  oauth2-server-1:
    image: "openjdk:8"
    working_dir: /usr/local/springboot
    command: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]
    volumes:
    - ./build/libs/spring-boot-oauth2-server-0.0.1-SNAPSHOT.jar:/usr/local/springboot/app.jar
    environment:
     - SPRING_PROFILES_ACTIVE=server-1
    networks:
     - mynet
networks:
  mynet:
    external: true
    name: spring-boot-oauth2-server_mynet
