version: '3.7'
services:
  redis:
    image: "redis:latest"
    ports:
     - "6379:6379"
  mysql:
    image: "mysql:latest"
    ports:
     - "3306:3306"
  openldap:
    image: "osixia/openldap:latest"
    ports:
     - "389:389"
     - "689:689"
