version: '3.7'

services:
  build:
    context: .
    image: "oauth2-server:latest"
  haproxy:
    image: "haproxy:1.8.14"
    ports:
     - "80:80"
    volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  oauth2-server:
    image: "oauth2-server:latest"
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    volumes:
     - type: bind
       source: ./
       target: /usr/local/springboot
    working_dir: /usr/local/springboot
    networks:
      mynet:
        aliases:
         - oauth2-server
  portainer:
    image: "portainer/portainer"
    ports:
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
  redis:
    image: "redis"
    ports:
     - "6379:6379"
    volumes:
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
    networks:
      mynet:
        aliases:
         - redis
  mysql:
    image: "mysql"
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=passw0rd
     - MYSQL_DATABASE=oauth2
     - MYSQL_USER=oauth2-server
     - MYSQL_PASSWORD=passw0rd
    volumes:
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
    networks:
     - mynet
  openldap:
    image: "osixia/openldap"
    ports:
     - "389:389"
     - "689:689"
    environment:
     - LDAP_ORGANISATION=Spring boot OAuth2 POC
     - LDAP_DOMAIN1=hung.org
     - LDAP_BASE_DN1=dc=hung,dc=org
     - LDAP_ADMIN_PASSWORD=passw0rd
    volumes:
     - /etc/localtime:/etc/localtime
     - /etc/timezone:/etc/timezone
    networks:
     - mynet
  openldap-admin:
    image: "osixia/phpldapadmin"
    ports:
     - "6443:443"
    environment:
     - PHPLDAPADMIN_LDAP_HOSTS=openldap
    links:
     - openldap
networks:
  mynet:
    driver: bridge
    attachable: true
