version: '3.7'

services:
  haproxy:
    image: "haproxy:1.8.14"
    ports:
     - "80:80"
    volumes:
     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
     - mynet
  oauth2-server-1:
    build:
      context: .
    environment:
     - SPRING_PROFILES_ACTIVE=server-1
    networks:
     - mynet
  oauth2-server-2:
    build:
      context: .
    environment:
     - SPRING_PROFILES_ACTIVE=server-2
    networks:
     - mynet
networks:
  mynet:
    external: true
    name: spring-boot-oauth2-server_mynet
