version: '3.7'
services:
  redis:
    image: "redis:latest"
    ports:
     - "6379:6379"
  mysql:
    image: "mysql:latest"
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=passw0rd
     - MYSQL_DATABASE=oauth2
     - MYSQL_USER=oauth2-server
     - MYSQL_PASSWORD=passw0rd
  openldap:
    image: "osixia/openldap:latest"
    ports:
     - "389:389"
     - "689:689"
