server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/oauth2?userSSL=false
    username: oauth2-server
    password: passw0rd
    initialization-mode: never 
    platform: mysql
    schema:
    - classpath:scheme-mysql.sql
    hikari:
      maximum-pool-size: 5 
      minimum-idle: 3
  
  redis:
    host: redis
    port: 6379
    
  ldap:
    urls:
    - ldap://openldap:389
    username: admin 
    password: passw0rd
    base: dc=hung,dc=org



logging:
  level:
    org.springframework.security.ldap: debug
    org.springframework.jdbc.datasource: debug
    com.zaxxer.hikari: debug
